# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb5b5da230f7f5b51adbe4593061c4810ccea23b73f8ab82e9693fa4086161e2ec43954a31a3e83b6ecd350d2af1c5b6872c3bf5a1ddc9bbc2c5a25add055cee

test:
  secret_key_base: bed98733490faf1820ec6de35d4be6e0d75a93a87b80356a010cbf0b8b2d665aaa517e35d5abf45f0ac653bb7d89da221b4253095b15ab54a41dd98d7a381583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
